name: Build RDR2 Mod 2026
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install OpenOrbis Toolchain
        run: |
          wget https://github.com/0x199/OpenOrbis-PS4-Toolchain/
          sudo tar -xvf OpenOrbis-PS4-Toolchain.tar.gz -C /opt
          echo "OO_PS4_TOOLCHAIN=/opt/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV

      - name: Build Mod PRX
        run: |
          export PATH=$PATH:$OO_PS4_TOOLCHAIN/bin
          make

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: JohnBodyguard-Plugin
          path: ./JohnBodyguard.prx
