name: Build RDR2 Mod
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OpenOrbis Toolchain
        run: |
          wget https://github.com
          sudo tar -xvf OpenOrbis-PS4-Toolchain.tar.gz -C /opt
          echo "OO_PS4_TOOLCHAIN=/opt/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV

      - name: Build Mod PRX
        run: |
          export PATH=$PATH:$OO_PS4_TOOLCHAIN/bin
          make

      - name: Upload Mod
        uses: actions/upload-artifact@v3
        with:
          name: JohnBodyguard-Mod
          path: ./JohnBodyguard.prx
