name: Build RDR2 Mod
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      -       - name: Install OpenOrbis Toolchain
        run: |
          # Usa curl com -L para seguir redirecionamentos e -o para salvar com o nome correto
          curl -L https://github.com -o toolchain.tar.gz
          
          # Verifica se o arquivo baixado é realmente um tar (evita o erro do index.html)
          if ! tar -ztf toolchain.tar.gz >/dev/null 2>&1; then
            echo "ERRO: O download falhou ou baixou um arquivo HTML em vez do toolchain."
            exit 1
          fi

          sudo mkdir -p /opt/OpenOrbis/PS4Toolchain
          sudo tar -xvf toolchain.tar.gz -C /opt
          echo "OO_PS4_TOOLCHAIN=/opt/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV


      - name: Build Mod PRX
        run: |
          export PATH=$PATH:$OO_PS4_TOOLCHAIN/bin
          make

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: JohnBodyguard-Mod
          path: ./*.prx
